/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import flexcup.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.FileReader;
import java_cup.runtime.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Admin
 */
public class Principal extends javax.swing.JFrame {
    AnalizadorSintac Sintac;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        btnLex.addActionListener(e -> AnalizarLex());
        btnSintac.addActionListener(e -> AnalizarSin());
        btnExec.addActionListener(e -> Exect());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TxtCadenas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnLex = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TxtLexico = new javax.swing.JTextArea();
        btnSintac = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInstance = new javax.swing.JTable();
        btnExec = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPila = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TxtRes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtCadenas.setColumns(20);
        TxtCadenas.setRows(5);
        jScrollPane1.setViewportView(TxtCadenas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, 280));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Cadena a Analizar Lexicamente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnLex.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLex.setText("Analizar Lexicamente");
        getContentPane().add(btnLex, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        TxtLexico.setColumns(20);
        TxtLexico.setRows(5);
        jScrollPane5.setViewportView(TxtLexico);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 460, 310));

        btnSintac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSintac.setText("Analizar Sintacticamente");
        getContentPane().add(btnSintac, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        tblInstance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Symb-Func", "Nombre", "Val", "Funcion"
            }
        ));
        jScrollPane2.setViewportView(tblInstance);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 310));

        btnExec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExec.setText("Ejecutar codigo");
        getContentPane().add(btnExec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        tblPila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Datum", "Valor", "Simbolo", "Tipo", "Valor"
            }
        ));
        jScrollPane3.setViewportView(tblPila);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 450, 310));

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane4.setViewportView(txtResult);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 380, 300));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("PILA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));

        TxtRes.setColumns(20);
        TxtRes.setRows(5);
        jScrollPane6.setViewportView(TxtRes);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 400, 280, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public void AnalizarLex(){
        Symbol simb;
        String Lexema = new String();
        String CadAux = new String();
        File InArch = new File("ArchEnt.txt");
        PrintWriter escribir;
        TxtLexico.setText("");
        try{
            escribir = new PrintWriter(InArch);
            escribir.print(TxtCadenas.getText());
            escribir.close();
        }
        catch(FileNotFoundException ex){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE,null,ex);
        }
        
        try{
            Reader Lector;
            Lector = new FileReader("ArchEnt.txt");
            
            AnalizadorLexico Lex = new AnalizadorLexico(Lector);
            Lex.Maquina = new MaquinaHoc4();
            do{
                simb = Lex.next_token();
                CadAux = Integer.toString(simb.sym);
                Lexema = Lex.yytext();
                if(simb.sym == AnalizadorSintacSym.EOF)
                    CadAux = "Token: " + CadAux + " \t identToken: FIN";
                else{
                    switch(simb.sym){
                        case AnalizadorSintacSym.SEMIC:
                            CadAux = "Token: " + CadAux + " \t identToken: SEMIC \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.NUM:
                            CadAux = "Token: " + CadAux + " \t identToken: NUM \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.CONST_PRED:
                            CadAux = "Token: " + CadAux + " \t identToken: CONST_PRED \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.BLTIN:
                            CadAux = "Token: " + CadAux + " \t identToken: BLTIN \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.OpAsig:
                            CadAux = "Token: " + CadAux + " \t identToken: OpAsig \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.OpSum:
                            CadAux = "Token: " + CadAux + " \t identToken: OpSum \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.OpRes:
                            CadAux = "Token: " + CadAux + " \t identToken: OpRes \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.OpDiv:
                            CadAux = "Token: " + CadAux + " \t identToken: OpDiv \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.OpProd:
                            CadAux = "Token: " + CadAux + " \t identToken: OpProd \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.ParIzq:
                            CadAux = "Token: " + CadAux + " \t identToken: ParIzq \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.ParDer:
                            CadAux = "Token: " + CadAux + " \t identToken: ParDer \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.error:
                            CadAux = "Token: " + CadAux + " \t identToken: ERROR \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.VAR:
                            CadAux = "Token: " + CadAux + " \t identToken: VAR \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.OpPot:
                            CadAux = "Token: " + CadAux + " \t identToken: OpPot \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.OpMen:
                            CadAux = "Token: " + CadAux + " \t identToken: OpMen \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.OpMayIg:
                            CadAux = "Token: " + CadAux + " \t identToken: OpMayIg \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.OpMenIg:
                            CadAux = "Token: " + CadAux + " \t identToken: OpMenIg \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.OpIgual:
                            CadAux = "Token: " + CadAux + " \t identToken: OpIgual \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.OpDif:
                            CadAux = "Token: " + CadAux + " \t identToken: OpDif \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.OpMay:
                            CadAux = "Token: " + CadAux + " \t identToken: OpMay \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.IF:
                            CadAux = "Token: " + CadAux + " \t identToken: IF \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.ELSE:
                            CadAux = "Token: " + CadAux + " \t identToken: ELSE \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.LLAVE_IZQ:
                            CadAux = "Token: " + CadAux + " \t identToken: LLAVE_IZQ \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.WHILE:
                            CadAux = "Token: " + CadAux + " \t identToken: WHILE \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.LLAVE_DER:
                            CadAux = "Token: " + CadAux + " \t identToken: LLAVE_DER \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.FUNCTION:
                            CadAux = "Token: " + CadAux + " \t identToken: FUNCTION \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.PROCEDURE:
                            CadAux = "Token: " + CadAux + " \t identToken: PROCEDURE \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.RETURN:
                            CadAux = "Token: " + CadAux + " \t identToken: RETURN \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.COMA:
                            CadAux = "Token: " + CadAux + " \t identToken: COMA \t Lexema:" + Lexema + "\n";
                            break;
                    }
                    TxtLexico.append(CadAux);
                }
            }while(simb.sym!= AnalizadorSintacSym.EOF);
        }
        catch(IOException ex){
            TxtLexico.append("Catch");
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE,null,ex);
        }
        TxtLexico.repaint();
    }
    
    public void AnalizarSin(){
        
        String CadAux = new String();
        String CadInst = new String();
        String Name = new String();
        String Valor = new String();
        String ptrFunc = new String();
        Object os[] = new Object[4];
        InstruProg Instruc;
        txtResult.setText("");
        AnalizadorLexico Lex = null;
        DefaultTableModel Modelo = (DefaultTableModel) tblInstance.getModel();
        try{
            Lex = new AnalizadorLexico(new FileReader("ArchEnt.txt"));
        } catch(FileNotFoundException ex){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE,null,ex);
        }
        
        Modelo.setRowCount(0);
        try{
           Sintac = new AnalizadorSintac(Lex);
           Sintac.FrmMen = this;
           Sintac.Maq = new MaquinaHoc4();
           Lex.Maquina = Sintac.Maq;
           SymbolHoc s;
           Iterator it = Lex.Maquina.Tabs.ListaSymb.iterator();
           while(it.hasNext()){
               s=(SymbolHoc) it.next();
               CadAux = "\n------------------\n \t Symbol:" + s.Nom + "\n------------------\n";
               TxtLexico.append(CadAux);
           }


Object result = Sintac.parse().value;
    InstruProg in2 = new InstruProg();
    in2.TipInst = EnumTipInst.INSTRUC;
    in2.Instruccion = EnumMaq.STOP;
    Sintac.Maq.code(in2);
System.out.println("Codigo generado: " + Sintac.Maq.progp);
           agregarResultado("\n FIN DEL ANALISIS SINTACTICO");
           for(int i=0; i<Sintac.Maq.progp;i++){
               CadInst = ""; Name = ""; Valor = ""; ptrFunc = "";
               Instruc=Sintac.Maq.Prog[i];
               CadAux = "\n------------------ERROR------------------\n";
               if (Instruc.Instruccion == null && Instruc.direccion >= 0) {
                 CadInst = "DIR";
                 Valor = Integer.toString(Instruc.direccion);

                 os[0] = CadInst;
                 os[1] = "";
                 os[2] = Valor;
                 os[3] = "";

                 Modelo.addRow(os);
                 continue;
                }
               switch(Instruc.TipInst){
                   case INSTRUC:
                       switch(Instruc.Instruccion){
                           case ADD:
                               CadAux = "instruc ADD";
                               CadInst="ADD";
                               break;
                            case ASIGN:
                               CadAux = "instruc ASIGN";
                               CadInst="ASIGN";
                               break;
                            case BLTIN:
                               CadAux = "instruc BLTIN";
                               CadInst="BLTIN";
                               break;
                            case CONSTPUSH:
                               CadAux = "instruc CONSTPUSH";
                               CadInst="CONSTPUSH";
                               break;
                            case DIV:
                               CadAux = "instruc DIV";
                               CadInst="DIV";
                               break;
                            case EVAL:
                               CadAux = "instruc EVAL";
                               CadInst="EVAL";
                               break;
                            case MUL:
                               CadAux = "instruc MUL";
                               CadInst="MUL";
                               break;
                            case NEGATE:
                               CadAux = "instruc NEGATE";
                               CadInst="NEGATE";
                               break;
                            case POWER:
                               CadAux = "instruc POWER";
                               CadInst="POWER";
                               break;
                            case PRINT:
                               CadAux = "instruc PRINT";
                               CadInst="PRINT";
                               break;
                            case STOP:
                               CadAux = "instruc STOP";
                               CadInst="STOP";
                               break;
                             case SUB:
                               CadAux = "instruc SUB";
                               CadInst="SUB";
                               break;
                            case VARPUSH:
                               CadAux = "instruc VARPUSH";
                               CadInst="VARPUSH";
                               break;
                            case GT:
                                CadInst = "GT";
                                break;
                            case LT:
                                CadInst = "LT";
                                break;
                            case GE:
                                CadInst = "GE";
                                break;
                            case LE:
                                CadInst = "LE";
                                break;
                            case EQ:
                                CadInst = "EQ";
                                break;
                            case NE:
                                CadInst = "NE";
                                break;
                            case JUMP:
                                CadInst = "JUMP";
                                break;
                            case JUMP_TRUE:
                                CadInst = "JUMP_TRUE";
                                break;      
                            case JUMP_FALSE:
                                CadInst = "JUMP_FALSE";
                                break;
                       }
                       CadAux+= "\n";
                       TxtLexico.append(CadAux);
                       break;
                   case BLTIN:
                       CadInst="FuncPred";
                       switch(Instruc.Func_BLTIN){
                           case SIN:
                               CadAux = "Bltin SIN";
                               Name = "SIN"; 
                               ptrFunc = "SIN";
                               break;
                           case COS:
                               CadAux = "Bltin COS";
                               Name = "COS"; 
                               ptrFunc = "COS";
                               break;
                           case ATAN:
                               CadAux = "Bltin ATAN";
                               Name = "ATAN"; 
                               ptrFunc = "ATAN";
                               break;
                           case LOG: 
                               CadAux = "Bltin LOG";
                               Name = "LOG"; 
                               ptrFunc = "LOG";
                               break;
                           case LOG10:
                               CadAux = "Bltin LOG10";
                               Name = "LOG10"; 
                               ptrFunc = "LOG10";
                               break;
                           case EXP:
                               CadAux = "Bltin EXP";
                               Name = "EXP"; 
                               ptrFunc = "EXP";
                               break;
                           case SQRT:
                               CadAux = "Bltin SQRT";
                               Name = "SQRT"; 
                               ptrFunc = "SQRT";
                               break; 
                           case INT: 
                               CadAux = "Bltin INT";
                               Name = "INT"; 
                               ptrFunc = "INT";
                               break;
                           case ABS:
                               CadAux = "Bltin ABS";
                               Name = "ABS"; 
                               ptrFunc = "ABS";
                               break;
                       }
                       CadAux+= "\n";
                       TxtLexico.append(CadAux);
                       break;
                   case SYMBOL:
                       CadAux = "Symbol Name:" + Instruc.SymHoc.Nom + "Val=" + Float.toString(Instruc.SymHoc.val);
                       CadAux+= "\n";
                       TxtLexico.append(CadAux);
                       switch(Instruc.SymHoc.TipoSim){
                           case VAR:
                                CadInst="VAR";
                               Name = Instruc.SymHoc.Nom;
                               Valor = Float.toString(Instruc.SymHoc.val);
                               ptrFunc = "";
                                break;
                           case UNDEF:
                                CadInst="UNDEF";
                               Name = Instruc.SymHoc.Nom;
                               Valor = "--";
                               ptrFunc = "";
                                break;
                           case CONST_NUM:
                                CadInst="CONST_NUM";
                               Name = Instruc.SymHoc.Nom;
                               Valor = Float.toString(Instruc.SymHoc.val);
                               ptrFunc = "";
                                break;
                           case CONST_PRED:
                                CadInst="CONST_PRED";
                               Name = Instruc.SymHoc.Nom;
                               Valor = Float.toString(Instruc.SymHoc.val);
                               ptrFunc = "";
                                break;
                       }
                       break;
                       case null:
                            CadInst = "DIR";
                            Valor = Integer.toString(Instruc.direccion);
                            break;
               }
               os[0]=(Object)CadInst ;
               os[1]=(Object)Name ;
               os[2]=(Object)Valor ;
               os[3]=(Object)ptrFunc ;
               Modelo.addRow(os);
           }
        } catch(Exception ex){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    public void agregarResultado(String texto){
    txtResult.append(texto + "\n");
}
    public void Exect(){
        System.out.println("progp = " + Sintac.Maq.progp);

for(int i = 0; i < Sintac.Maq.progp; i++){
    System.out.println(
        i + " -> " +
        (Sintac.Maq.Prog[i] == null ?
         "NULL" :
         Sintac.Maq.Prog[i].TipInst)
    );
}
        String Cad1 = new String();        
        String Cad2 = new String();        
        String Cad3 = new String();        
        String Cad4 = new String();        
        String Cad5 = new String();
        Object os[] = new Object[5];
        DefaultTableModel Modelo = (DefaultTableModel) tblPila.getModel();
        Modelo.setNumRows(0);
        TxtRes.setText("");
        os[0]=Cad1;
        os[1]=Cad2;
        os[2]=Cad3;
        os[3]=Cad4;
        os[4]=Cad5;
        Modelo.addRow(os);
        Modelo.fireTableDataChanged();
        Sintac.Maq.exec(0, TxtRes, this.tblPila);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtCadenas;
    private javax.swing.JTextArea TxtLexico;
    private javax.swing.JTextArea TxtRes;
    private javax.swing.JButton btnExec;
    private javax.swing.JButton btnLex;
    private javax.swing.JButton btnSintac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tblInstance;
    private javax.swing.JTable tblPila;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
