/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import flexcup.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.FileReader;
import java_cup.runtime.*;


/**
 *
 * @author Admin
 */
public class Principal extends javax.swing.JFrame {
    AnalizadorSintac Sintac;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        btnLex.addActionListener(e -> AnalizarLex());
        btnSintac.addActionListener(e -> AnalizarSin());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TxtCadenas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnLex = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        TxtLexico = new javax.swing.JTextArea();
        btnSintac = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtCadenas.setColumns(20);
        TxtCadenas.setRows(5);
        jScrollPane1.setViewportView(TxtCadenas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, 280));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Cadena a Analizar Lexicamente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnLex.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLex.setText("Analizar Lexicamente");
        getContentPane().add(btnLex, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane4.setViewportView(txtResult);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 380, 300));

        TxtLexico.setColumns(20);
        TxtLexico.setRows(5);
        jScrollPane5.setViewportView(TxtLexico);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 460, 310));

        btnSintac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSintac.setText("Analizar Sintacticamente");
        getContentPane().add(btnSintac, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public void AnalizarLex(){
        Symbol simb;
        String Lexema = new String();
        String CadAux = new String();
        File InArch = new File("ArchEnt.txt");
        PrintWriter escribir;
        TxtLexico.setText("");
        try{
            escribir = new PrintWriter(InArch);
            escribir.print(TxtCadenas.getText());
            escribir.close();
        }
        catch(FileNotFoundException ex){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE,null,ex);
        }
        
        try{
            Reader Lector;
            Lector = new FileReader("ArchEnt.txt");
            
            AnalizadorLexico Lex = new AnalizadorLexico(Lector);
            do{
                simb = Lex.next_token();
                CadAux = Integer.toString(simb.sym);
                Lexema = Lex.yytext();
                if(simb.sym == AnalizadorSintacSym.EOF)
                    CadAux = "Token: " + CadAux + " \t identToken: FIN";
                else{
                    switch(simb.sym){
                        case AnalizadorSintacSym.SEMIC:
                            CadAux = "Token: " + CadAux + " \t identToken: SEMIC \t Lexema:" + Lexema + "\n";
                            break;
                        case AnalizadorSintacSym.NUM:
                            CadAux = "Token: " + CadAux + " \t identToken: NUM \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.CONST_PRED:
                            CadAux = "Token: " + CadAux + " \t identToken: CONST_PRED \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.BLTIN:
                            CadAux = "Token: " + CadAux + " \t identToken: BLTIN \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.OpAsig:
                            CadAux = "Token: " + CadAux + " \t identToken: OpAsig \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.OpSum:
                            CadAux = "Token: " + CadAux + " \t identToken: OpSum \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.OpRes:
                            CadAux = "Token: " + CadAux + " \t identToken: OpRes \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.OpDiv:
                            CadAux = "Token: " + CadAux + " \t identToken: OpDiv \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.OpProd:
                            CadAux = "Token: " + CadAux + " \t identToken: OpProd \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.ParIzq:
                            CadAux = "Token: " + CadAux + " \t identToken: ParIzq \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.ParDer:
                            CadAux = "Token: " + CadAux + " \t identToken: ParDer \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.error:
                            CadAux = "Token: " + CadAux + " \t identToken: ERROR \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.VAR:
                            CadAux = "Token: " + CadAux + " \t identToken: VAR \t Lexema:" + Lexema+ "\n";
                            break;
                        case AnalizadorSintacSym.OpPot:
                            CadAux = "Token: " + CadAux + " \t identToken: OpPot \t Lexema:" + Lexema+ "\n";
                            break;
                    }
                    TxtLexico.append(CadAux);
                }
            }while(simb.sym!= AnalizadorSintacSym.EOF);
        }
        catch(IOException ex){
            TxtLexico.append("Catch");
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE,null,ex);
        }
        TxtLexico.repaint();
    }
    
    public void AnalizarSin(){
        String CadAux = new String();
        String CadInst = new String();
        String Name = new String();
        String Valor = new String();
        String ptrFunc = new String();
        
        txtResult.setText("");
        AnalizadorLexico Lex = null;
        try{
            Lex = new AnalizadorLexico(new FileReader("ArchEnt.txt"));
        } catch(FileNotFoundException ex){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE,null,ex);
        }
        Sintac = new AnalizadorSintac(Lex);
        
        Sintac.FrmMen = this;
        
        try{
            Object result = Sintac.parse().value;
        } catch(Exception ex){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    public void agregarResultado(String texto){
    txtResult.append(texto + "\n");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtCadenas;
    private javax.swing.JTextArea TxtLexico;
    private javax.swing.JButton btnLex;
    private javax.swing.JButton btnSintac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
