
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package flexcup;

import src.*;
import java_cup.runtime.*;
import java.io.FileReader;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class AnalizadorSintac extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return AnalizadorSintacSym.class;
}

  /** Default constructor. */
  @Deprecated
  public AnalizadorSintac() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public AnalizadorSintac(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintac(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\020\000\002\002\004\000\002\002\004\000\002\002" +
    "\005\000\002\003\005\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\005\000" +
    "\002\004\005\000\002\004\005\000\002\004\005\000\002" +
    "\004\005\000\002\004\006\000\002\004\004\000\002\004" +
    "\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\040\000\016\005\010\012\014\015\004\016\006\017" +
    "\005\020\013\001\002\000\020\004\ufffd\005\ufffd\006\ufffd" +
    "\007\ufffd\011\ufffd\013\ufffd\014\ufffd\001\002\000\020\004" +
    "\ufffb\005\ufffb\006\ufffb\007\ufffb\011\ufffb\013\ufffb\014\ufffb" +
    "\001\002\000\022\004\ufffc\005\ufffc\006\ufffc\007\ufffc\010" +
    "\041\011\ufffc\013\ufffc\014\ufffc\001\002\000\020\002\036" +
    "\005\010\012\014\015\004\016\006\017\005\020\013\001" +
    "\002\000\016\005\010\012\014\015\004\016\006\017\005" +
    "\020\013\001\002\000\020\004\ufffa\005\ufffa\006\ufffa\007" +
    "\ufffa\011\ufffa\013\ufffa\014\ufffa\001\002\000\016\004\021" +
    "\005\020\006\022\007\017\011\016\014\034\001\002\000" +
    "\004\012\031\001\002\000\016\005\010\012\014\015\004" +
    "\016\006\017\005\020\013\001\002\000\016\004\021\005" +
    "\020\006\022\007\017\011\016\013\023\001\002\000\016" +
    "\005\010\012\014\015\004\016\006\017\005\020\013\001" +
    "\002\000\016\005\010\012\014\015\004\016\006\017\005" +
    "\020\013\001\002\000\016\005\010\012\014\015\004\016" +
    "\006\017\005\020\013\001\002\000\016\005\010\012\014" +
    "\015\004\016\006\017\005\020\013\001\002\000\016\005" +
    "\010\012\014\015\004\016\006\017\005\020\013\001\002" +
    "\000\020\004\ufff5\005\ufff5\006\ufff5\007\ufff5\011\ufff5\013" +
    "\ufff5\014\ufff5\001\002\000\020\004\ufff7\005\ufff7\006\ufff7" +
    "\007\ufff7\011\016\013\ufff7\014\ufff7\001\002\000\020\004" +
    "\ufff9\005\ufff9\006\022\007\017\011\016\013\ufff9\014\ufff9" +
    "\001\002\000\020\004\ufff8\005\ufff8\006\022\007\017\011" +
    "\016\013\ufff8\014\ufff8\001\002\000\020\004\ufff6\005\ufff6" +
    "\006\ufff6\007\ufff6\011\016\013\ufff6\014\ufff6\001\002\000" +
    "\020\004\ufff2\005\ufff2\006\ufff2\007\ufff2\011\016\013\ufff2" +
    "\014\ufff2\001\002\000\016\005\010\012\014\015\004\016" +
    "\006\017\005\020\013\001\002\000\016\004\021\005\020" +
    "\006\022\007\017\011\016\013\033\001\002\000\020\004" +
    "\ufff4\005\ufff4\006\ufff4\007\ufff4\011\ufff4\013\ufff4\014\ufff4" +
    "\001\002\000\020\002\001\005\001\012\001\015\001\016" +
    "\001\017\001\020\001\001\002\000\020\004\ufff3\005\ufff3" +
    "\006\ufff3\007\ufff3\011\016\013\ufff3\014\ufff3\001\002\000" +
    "\004\002\000\001\002\000\016\004\021\005\020\006\022" +
    "\007\017\011\016\014\040\001\002\000\020\002\uffff\005" +
    "\uffff\012\uffff\015\uffff\016\uffff\017\uffff\020\uffff\001\002" +
    "\000\016\005\010\012\014\015\004\016\006\017\005\020" +
    "\013\001\002\000\020\004\021\005\020\006\022\007\017" +
    "\011\016\013\ufffe\014\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\040\000\010\002\006\003\010\004\011\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\003\010\004\036\001\001\000\006\003\010\004\034\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\003\010\004\014\001\001\000\002\001\001\000" +
    "\006\003\010\004\027\001\001\000\006\003\010\004\026" +
    "\001\001\000\006\003\010\004\025\001\001\000\006\003" +
    "\010\004\024\001\001\000\006\003\010\004\023\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\003\010\004\031\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\003\010\004" +
    "\041\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintac$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintac$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintac$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public Principal FrmMen;
    public Float var[] = new Float[26];
    public MaqHOC Maq; 

    public void RepError(String Mensaje, Object Info){
        StringBuilder m = new StringBuilder("Error");
        if(Info instanceof java_cup.runtime.Symbol){
            java_cup.runtime.Symbol s = (java_cup.runtime.Symbol) Info;
            if(s.left>=0){
                m.append(" en la linea " + (s.left+1));
                if(s.right>=0)
                    m.append(", columna " + (s.right+1));
            }
        }
        m.append(" : " + Mensaje);
        System.err.println(m);
    }
    
    public void RepFatError(String Mensaje, Object Info){
        RepError(Mensaje,Info);
        System.exit(1);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$AnalizadorSintac$actions {
  private final AnalizadorSintac parser;

  /** Constructor */
  CUP$AnalizadorSintac$actions(AnalizadorSintac parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintac$do_action_part00000000(
    int                        CUP$AnalizadorSintac$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintac$parser,
    java.util.Stack            CUP$AnalizadorSintac$stack,
    int                        CUP$AnalizadorSintac$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintac$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintac$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // list ::= expr SEMIC 
            {
              Object RESULT =null;
		
    InstruProg in1 = new InstruProg();
    in1.TipInst = EnumTipInst.INSTRUC;
    in1.Instruccion = EnumMaq.PRINT;
    /*
    InstruProg in2 = new InstruProg();
    in2.TipInst = EnumTipInst.INSTRUC;
    in2.Instruccion = EnumMaq.STOP;*/

    Maq.code(in1);

              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("list",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= list EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintac$parser.done_parsing();
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // list ::= list expr SEMIC 
            {
              Object RESULT =null;
		
    InstruProg in1 = new InstruProg();
    in1.TipInst = EnumTipInst.INSTRUC;
    in1.Instruccion = EnumMaq.PRINT;
    /*
    InstruProg in2 = new InstruProg();
    in2.TipInst = EnumTipInst.INSTRUC;
    in2.Instruccion = EnumMaq.STOP;*/

    Maq.code(in1);

              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("list",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // asign ::= VAR OpAsig expr 
            {
              Integer RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-2)).right;
		SymbolHoc v = (SymbolHoc)((java_cup.runtime.Symbol) CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-2)).value;
		
                InstruProg in1 = new InstruProg(); 
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.VARPUSH;

                InstruProg in2 = new InstruProg();
                in2.TipInst = EnumTipInst.SYMBOL;
                in2.SymHoc = v;

                 InstruProg in3 = new InstruProg();
                in3.TipInst = EnumTipInst.INSTRUC;
                in3.Instruccion = EnumMaq.ASIGN;
                RESULT = Maq.code3(in1, in2, in3);
                  
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("asign",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // expr ::= NUM 
            {
              Integer RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).right;
		SymbolHoc n = (SymbolHoc)((java_cup.runtime.Symbol) CUP$AnalizadorSintac$stack.peek()).value;
		
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.CONSTPUSH;

                InstruProg in2 = new InstruProg();
                in2.TipInst = EnumTipInst.SYMBOL;
                in2.SymHoc = n;
                RESULT = Maq.code2 (in1, in2);
                
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expr ::= VAR 
            {
              Integer RESULT =null;
		int Vleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).left;
		int Vright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).right;
		SymbolHoc V = (SymbolHoc)((java_cup.runtime.Symbol) CUP$AnalizadorSintac$stack.peek()).value;
		 
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.VARPUSH;
                
                InstruProg in2 = new InstruProg();
                in2.TipInst = EnumTipInst.SYMBOL;
                in2.SymHoc = V;
                
                InstruProg in3 = new InstruProg();
              
                in3.TipInst = EnumTipInst.INSTRUC;
                in3.Instruccion = EnumMaq.EVAL;

                RESULT = Maq.code3(in1, in2, in3);
                
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expr ::= CONST_PRED 
            {
              Integer RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).right;
		SymbolHoc n = (SymbolHoc)((java_cup.runtime.Symbol) CUP$AnalizadorSintac$stack.peek()).value;
		
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.CONSTPUSH;

                InstruProg in2 = new InstruProg();
                in2.TipInst = EnumTipInst.SYMBOL;
                in2.SymHoc = n;
                RESULT = Maq.code2(in1, in2);
                
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expr ::= asign 
            {
              Integer RESULT =null;
		int indleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).left;
		int indright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()).right;
		Integer ind = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSintac$stack.peek()).value;
		 RESULT = ind; 
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expr ::= expr OpSum expr 
            {
              Integer RESULT =null;
		
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.ADD;
                RESULT = Maq.code(in1);
                
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expr ::= expr OpRes expr 
            {
              Integer RESULT =null;
		
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.SUB;
                RESULT = Maq.code(in1);
                
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // expr ::= expr OpProd expr 
            {
              Integer RESULT =null;
		
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.MUL;
                RESULT = Maq.code(in1);
                
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // expr ::= expr OpDiv expr 
            {
              Integer RESULT =null;
		
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.DIV;
                RESULT = Maq.code(in1);
                
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // expr ::= ParIzq expr ParDer 
            {
              Integer RESULT =null;
		int indleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)).left;
		int indright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)).right;
		Integer ind = (Integer)((java_cup.runtime.Symbol) CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)).value;
		 RESULT = ind; 
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // expr ::= BLTIN ParIzq expr ParDer 
            {
              Integer RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-3)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-3)).right;
		SymbolHoc v = (SymbolHoc)((java_cup.runtime.Symbol) CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-3)).value;
		
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.BLTIN;
                
                InstruProg in2 = new InstruProg();
                in2.TipInst = EnumTipInst.BLTIN;
                in2.Func_BLTIN = v.FuncPred;
                RESULT = Maq.code2 (in1, in2);
                
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // expr ::= OpRes expr 
            {
              Integer RESULT =null;
		
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.NEGATE;
                RESULT = Maq.code(in1);
                
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expr ::= expr OpPot expr 
            {
              Integer RESULT =null;
		
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.POWER;
                RESULT = Maq.code(in1);
                
              CUP$AnalizadorSintac$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.elementAt(CUP$AnalizadorSintac$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintac$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintac$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$AnalizadorSintac$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintac$do_action(
    int                        CUP$AnalizadorSintac$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintac$parser,
    java.util.Stack            CUP$AnalizadorSintac$stack,
    int                        CUP$AnalizadorSintac$top)
    throws java.lang.Exception
    {
              return CUP$AnalizadorSintac$do_action_part00000000(
                               CUP$AnalizadorSintac$act_num,
                               CUP$AnalizadorSintac$parser,
                               CUP$AnalizadorSintac$stack,
                               CUP$AnalizadorSintac$top);
    }
}

}
