
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package flexcup;

/** CUP generated class containing symbol constants. */
public class AnalizadorSintacSym {
  /* terminals */
  public static final int NUM = 11;
  public static final int OpDiv = 5;
  public static final int ParDer = 9;
  public static final int SEMIC = 10;
  public static final int CONST_PRED = 13;
  public static final int EOF = 0;
  public static final int VAR = 12;
  public static final int OpProd = 4;
  public static final int OpSum = 2;
  public static final int OpRes = 3;
  public static final int OpAsig = 6;
  public static final int OpPot = 7;
  public static final int error = 1;
  public static final int BLTIN = 14;
  public static final int NEGUNAR = 15;
  public static final int ParIzq = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OpSum",
  "OpRes",
  "OpProd",
  "OpDiv",
  "OpAsig",
  "OpPot",
  "ParIzq",
  "ParDer",
  "SEMIC",
  "NUM",
  "VAR",
  "CONST_PRED",
  "BLTIN",
  "NEGUNAR"
  };
}

