package flexcup;
import src.*;

import java_cup.runtime.*;
import java.io.FileReader;

class AnalizadorSintac;

parser code {:
    public Principal FrmMen;
    public Float var[] = new Float[26];
    public MaqHOC Maq; 

    public void RepError(String Mensaje, Object Info){
        StringBuilder m = new StringBuilder("Error");
        if(Info instanceof java_cup.runtime.Symbol){
            java_cup.runtime.Symbol s = (java_cup.runtime.Symbol) Info;
            if(s.left>=0){
                m.append(" en la linea " + (s.left+1));
                if(s.right>=0)
                    m.append(", columna " + (s.right+1));
            }
        }
        m.append(" : " + Mensaje);
        System.err.println(m);
    }
    
    public void RepFatError(String Mensaje, Object Info){
        RepError(Mensaje,Info);
        System.exit(1);
    }
:}

terminal OpSum, OpRes, OpProd, OpDiv, OpAsig, OpPot;
terminal ParIzq, ParDer, SEMIC;
terminal SymbolHoc NUM;
terminal SymbolHoc VAR;
terminal SymbolHoc CONST_PRED;
terminal SymbolHoc BLTIN;
terminal NEGUNAR;

non terminal list;
non terminal Integer asign, expr;

/*JERARQUIA DE OPERACIONES*/
precedence right OpAsig;
precedence left OpSum, OpRes;
precedence left OpProd, OpDiv;
precedence left NEGUNAR;
precedence right OpPot;

list ::= expr SEMIC
{:
    InstruProg in1 = new InstruProg();
    in1.TipInst = EnumTipInst.INSTRUC;
    in1.Instruccion = EnumMaq.PRINT;
    /*
    InstruProg in2 = new InstruProg();
    in2.TipInst = EnumTipInst.INSTRUC;
    in2.Instruccion = EnumMaq.STOP;*/

    Maq.code(in1);
:}
    | list expr SEMIC {:
    InstruProg in1 = new InstruProg();
    in1.TipInst = EnumTipInst.INSTRUC;
    in1.Instruccion = EnumMaq.PRINT;
    /*
    InstruProg in2 = new InstruProg();
    in2.TipInst = EnumTipInst.INSTRUC;
    in2.Instruccion = EnumMaq.STOP;*/

    Maq.code(in1);
:};
asign ::= VAR:v OpAsig expr {:
                InstruProg in1 = new InstruProg(); 
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.VARPUSH;

                InstruProg in2 = new InstruProg();
                in2.TipInst = EnumTipInst.SYMBOL;
                in2.SymHoc = v;

                 InstruProg in3 = new InstruProg();
                in3.TipInst = EnumTipInst.INSTRUC;
                in3.Instruccion = EnumMaq.ASIGN;
                RESULT = Maq.code3(in1, in2, in3);
                  :};

expr  ::= NUM:n {:
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.CONSTPUSH;

                InstruProg in2 = new InstruProg();
                in2.TipInst = EnumTipInst.SYMBOL;
                in2.SymHoc = n;
                RESULT = Maq.code2 (in1, in2);
                :}
    | VAR:V {: 
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.VARPUSH;
                
                InstruProg in2 = new InstruProg();
                in2.TipInst = EnumTipInst.SYMBOL;
                in2.SymHoc = V;
                
                InstruProg in3 = new InstruProg();
              
                in3.TipInst = EnumTipInst.INSTRUC;
                in3.Instruccion = EnumMaq.EVAL;

                RESULT = Maq.code3(in1, in2, in3);
                :}
    | CONST_PRED:n {:
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.CONSTPUSH;

                InstruProg in2 = new InstruProg();
                in2.TipInst = EnumTipInst.SYMBOL;
                in2.SymHoc = n;
                RESULT = Maq.code2(in1, in2);
                :}
    | asign:ind {: RESULT = ind; :}
    | expr OpSum expr {:
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.ADD;
                RESULT = Maq.code(in1);
                :}
    | expr OpRes expr {:
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.SUB;
                RESULT = Maq.code(in1);
                :}
    | expr OpProd expr {:
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.MUL;
                RESULT = Maq.code(in1);
                :}
    | expr OpDiv expr {:
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.DIV;
                RESULT = Maq.code(in1);
                :}
    | ParIzq expr:ind ParDer {: RESULT = ind; :}
    | BLTIN:v ParIzq expr ParDer {:
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.BLTIN;
                
                InstruProg in2 = new InstruProg();
                in2.TipInst = EnumTipInst.BLTIN;
                in2.Func_BLTIN = v.FuncPred;
                RESULT = Maq.code2 (in1, in2);
                :}
    | OpRes expr {:
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.NEGATE;
                RESULT = Maq.code(in1);
                :}
                %prec NEGUNAR
    | expr OpPot expr {:
                InstruProg in1 = new InstruProg();
                in1.TipInst = EnumTipInst.INSTRUC;
                in1.Instruccion = EnumMaq.POWER;
                RESULT = Maq.code(in1);
                :}
    ;
